id: I48BE5EE8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T12:46:29+00:00'
last_modified: '2022-06-10T08:39:32.036248+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21657
  title: དེབ་ཐེར་དམར་པོ་གསར་མ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    34DF:
      image_group_id: I1GS105609
      title: Volume 1 of deb ther dmar po gsar ma
      total_pages: 118
      order: 1
      base_file: 34DF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
